### PR TITLE
initial draft and image for SSH pt3

### PR DESCRIPTION
**Pull request by srpsco**
Jacob

here is my draft for tomorrows post for your review and comments. Note there is an image included which will need the link corrected.

### CODE REVIEW

**Comment by jacobm001** [comment]
I'm fairly certain line 39 is a mistake. `sudo /etc/issue.net`

Other than that, it looks good.

**Comment by srpsco** [comment]
Jacob,

Nice catch it should be:

sudo nano /etc/issue.net

Do you want to fix it or want me to fix it?

Thanks,

Steve

**Comment by jacobm001** [comment]
I prefer authors update their pull requests. Otherwise I'm accepting and
then changing it after. That seems like it makes me less accountable in
general.

**Comment by srpsco** [comment]
Done and agreed

**Pull request merged**
