### PR TITLE
Create 2016-05-18_Setting_Up_LAMP.md

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by jacobm001** [comment]
It looks good overall! There are a few things that I think should be edited, but this is a great start. :)

---

>  I would suggest you try to find a headless version of Raspbian.

I'm not a fan of this wording. It makes it sound like there isn't a readily available, officially supported headless image. [Raspbian Jessie Lite](https://www.raspberrypi.org/downloads/raspbian/) was designed to be a minimal headless system. I think we should name and reference it.

---

> If you're on Windows, you'll want to use a tool called Rufus to copy the image onto your card.

Why Rufus and not Win32DiskImager, which is what the Foundation suggests? I'm not opposed to Rufus, but if you're going out from the norm, I'm curious as to the motivation behind the divergence.

---

The bit about `mysql_secure_installation` is great! I avoid MySQL like the plague, and while I'm extremely proficient with most RDMS installations, I didn't know that command existed.

---

When installing `php5` I would suggest running `a2enmod php5` and then `service apache2 reload`. It's much lighter and will actually give you better error messages if something goes wrong.

---

HTTPS is such a big deal, I've been thinking _Let's Encrypt_ actually deserves its own article. I'm curious, does anyone think maybe this bit should be removed from this article, and someone (me maybe?) should write a separate article on that entirely? Leave it and expand on it in another?

**Comment by ghost** [comment]
I've updated the file in my branch. The commit notes give more detail as to what I changed and why I made those changes specifically.

**Comment by angussidney** [comment]
You know you can run Raspbian without a GUI as a sufficiently minimal system? Much easier to explain, you only need to tell them to run `sudo raspi-config`

**Comment by ghost** [comment]
@angussidney That disables the GUI log-in, yes, but it does not remove the bulky X packages. I just added a line in there saying they can skip the first step entirely if they already have Raspbian installed.

**Comment by jacobm001** [comment]
@angussidney: true, but if the system will be accessed remotely, those packages do nothing but use disk space, and worse, time/network I/O during upgrades. 

@brownsnake: My comment about changing the commands regarding the install for `php5` was that I thought it still needed to be expressly enabled for apache2. I might be wrong on that...

At this point I'm just waiting for @srpsco to give it a look over (he said he'd probably do it on friday) and then I'll accept the pull request.

**Comment by ghost** [comment]
Ah, okay. No, the setup process now enables the Apache mod for you, now. You just need to restart the service on your own.

**Comment by jacobm001** [comment]
@brownsnake: good to know! I'm just waiting for Raspbian to surprise me with a php7 upgrade. My Ubuntu Server upgrading to php7 sure caught me off guard the other day. :P

**Comment by srpsco** [comment]
OK a couple of comments:

the phpinfo() function call should be removed after verifying it works because it gives a lot of info to a potential hacker. 

I am a little uncomfortable with making this setup accessible from the internet as it is not properly hardened (no firewall, intrusion detection etc.), which are beyond the scope of this post. Perhaps the best way to handle this is to change the potential usage to development or use as an intranet, and removing the section about port forwarding etc. 

You don't verify that the site works with SSL as the final step. This comes under trust but verify.

Finally, I would like to see a short list of additional resources which provide more info.

**Comment by srpsco** [comment]
forgot to mention the email issue, correct me if I am wrong but setting the admin email in the virtual host definition will not work without additional setup on the Pi unless it is a local address (i.e. pi@localhost)

**Comment by ghost** [comment]
Alright, I will do one of two things to fix this up. I can either talk a bit about setting up iptables and fail2ban for hardening purposes, or I can take out all the bits about SSL, port forwarding, and opening this up to the internet and then write a separate post about "now that you have a local webserver, let's try making it available to others...". How would you suggest I continue?

**Comment by srpsco** [comment]
I think separating the two is the better approach, though you may want to leave SSL in the first part as it is useful for testing. Unless the certbot requires a internet routable IP. I would also mention either via title or in the body that this is part 1 and what part two will cover.

**Comment by srpsco** [comment]
Sorry all clicked close by accident.

**Comment by ghost** [comment]
The certbot does require an internet routable IP, as it does an A Record check to make sure that the domain routes to the same IP as the client requesting the certificate. I can talk about using self-signed certificates for local testing, but that might be more trouble than it's worth if they continue to part 2 of the guide and get a Let's Encrypt certificate.

**Comment by srpsco** [comment]
I agree, in that case I would leave it out of part 1.

**Comment by ghost** [comment]
Thanks for the merge! I'll write-up Part 2 later today, and then I'll get started in on the OwnCloud post.

**Pull request merged**
