### PR TITLE
Camera tutorial

### PR DESCRIPTION
**Pull request by angussidney**
The first article in my series. Feel free to edit!

### CODE REVIEW

**Comment by angussidney** [comment]
I hope I haven't done anything wrong, it should be OK.

**Comment by jacobm001** [comment]
@angussidney, this is a great contribution. The only thing I don't like is line 108. In general, I find the use of `-` uncomfortable to read, and I know it's often confusing for non-native speakers.

> Note that this command is different to `time.sleep()` - `wait_recording()` will throw an exception and stop if any errors are found (e.g. not enough space), wheras `time.sleep()` will continue anyway.

Is _wheras_ a regional spelling? If so, that's fine. Otherwise, I'd like that changed to _whereas_. And there's a misspelling on line 94, _miliseconds_.

If my understanding of pull requests is correct, you can make those edits within this same pull request correct?

**Comment by angussidney** [comment]
@jacobm001 Would this work fine?

> Note that `wait_recording()` is different to `time.sleep()`. `wait_recording()` will throw an exception and stop if any errors are found (e.g. not enough space), while `time.sleep()` will continue _even if_ errors are found, potentially causing even more problems.

You're right about wheras, I just can't spell :smile:

If you think this is fine, I'll push another commit (it should work with the pull request)

**Comment by jacobm001** [comment]
I think that's great. Go ahead and make the change and I'll accept it tomorrow ☺️

**Comment by angussidney** [comment]
Done!

**Pull request merged**
