### PR TITLE
Etckeeper

### PR DESCRIPTION
**Pull request by srpsco**
Jacob here is my post on etckeeper

### CODE REVIEW

**Comment by angussidney** [comment]
Any reason why you used bold instead of code highlighting for the git commands?

**Comment by srpsco** [comment]
no I could have used code but it can be problematic getting it to format correctly and with one liners it is just easier. If I included a multiline script I would have.

**Comment by jacobm001** [comment]
Looks good overall. I'll have to give it a try.  :)

**Comment by srpsco** [comment]
Since i did not cover Git should we plan a series on it? I do plan a post or quick link on Git customizations

**Comment by angussidney** [comment]
I might consider making a Git post sometime

**Pull request merged**
